export const EXPENSE_CLASSIFICATIONS = Object.freeze({
  GENERAL: 'GENERAL_EXPENSE',
  PROPERTY_OWN: 'PROPERTY_OWN_EXPENSE',
  UNIT: 'UNIT_EXPENSE',
});

export const EXPENSE_CLASSIFICATION_LIST = Object.freeze(
  Object.values(EXPENSE_CLASSIFICATIONS)
);
